#!/bin/bash
set -eu

SINK="" # leave empty for auto-detecting
PACMD_PATH="pacmd"
MAX_VOLUME=65536

function err() {
  echo "$@" 1>&2
  exit 1
}

if [[ -z $SINK ]] # sink autodetection
	then SINK=$( "$PACMD_PATH" dump | sed  -ne "s/set-default-sink \(.*\)/\1/p" )
fi

get_volume()
{
	echo $(( $( "$PACMD_PATH" dump | sed -ne "s/set-sink-volume $SINK \(0x[0-9a-f]\+\)/\1/p" ) ))
}

get_mute()
{
	"$PACMD_PATH" dump | sed -ne "s/set-sink-mute $SINK \(yes\|no\)/\1/p"
}

set_mute()
{
	"$PACMD_PATH" set-sink-mute $SINK $1 | sed -ne "s/\(>>> \)\+\(.*\)/\2/p"
}

read_volume() {

  MUTE=$( get_mute )
	if [[ $MUTE = "yes" ]]
		then echo 0
      return
	fi

  echo $(( $( get_volume ) * 100 / $MAX_VOLUME ))
}

read_active_sink() {
  pacmd list-sinks | grep "* index" | awk '{print $3}'
}

set_volume() {
  local volume="$1"
  local sink=`read_active_sink`
  pactl set-sink-volume ${sink} ${volume}%
}

toggle_sound() {

	MUTE=$( get_mute )
	if [[ $MUTE = "yes" ]]
		then set_mute no
	else
		set_mute yes
	fi

}

usage() {
  echo "volumectl [status|read|set|toggle|list-sinks|set-sink]
  Helper script to deal with volumes and sound output.

COMMANDS
  status
    Print either 'on' or 'muted' depending on the current state.
  read
    Prints the current volume in percent. If sound is currently muted,
    it will be printed as '0'.
  set
    Change the volume. Accepts either an absolute new value (e.g., 'set 75')
    or a relative change (e.g., 'set +5' or 'set -10').
  toggle
    Toggle sound (i.e., mute / unmute it).
  list-sinks
    Print a list of available outputs.
  set-sink
    Set the default sink.

TROUBLESHOOTING
  - When switching to a new sink, there is no audio anymore.
    A: Toggle audio output twice."
}

case "${1:-}" in
  status)
    MUTE=$( get_mute )
    if [[ $MUTE = "yes" ]] 
      then echo "muted"
    else  echo "on"
    fi
    ;;
  read)
    read_volume
    ;;
  set)
    maxvolume="${MAX_ALLOWED_VOLUME:-200}"
    volume="${2:-}"
    [[ -z "${volume}" ]] && err "no volume to set was specified"

    # for increase/decrease, calculate the new absolute value first
    case "${volume}" in
      '+'*|'-'*)
        current=`read_volume`
        volume=$((${current}${volume:0:1}${volume:1}))
    esac

    # make sure the new value is in bounds
    volume=$(($volume>0?$volume:0))
    volume=$(($volume<$maxvolume?$volume:$maxvolume))

    case "${volume}" in
      ''|*[!0-9]*)
        err "volume has to be a number"
        ;;
      *)
        set_volume ${volume}
        ;;
    esac
    ;;
  toggle)
    toggle_sound
    ;;
  list-sinks)
    pactl list short sinks
    ;;
  set-sink)
    sink=`echo "${2:-}" | awk '{print $1}'`
    case "${sink}" in
      ''|*[!0-9]*)
        err "sink has to be or start with the sink number"
        ;;
      *)
        if [[ $(type -P paswitch) ]]
          then
            paswitch ${sink}
        fi        
        pactl set-default-sink ${sink}
        ;;
    esac
    ;;
  *)
    usage && exit 1
    ;;
esac
